linters:
  enable-all: false
  disable-all: true
  enable:
    - deadcode
    - depguard
    - gocritic
    - gofmt
    - goimports
    - golint
    - gosimple
    - govet
    - ineffassign
    - misspell
    - scopelint
    - structcheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - staticcheck

issues:
  exclude-use-default: false