linters:
  enable-all: false
  disable-all: true
  enable:
    - errcheck
    - deadcode
    - depguard
    - gocritic
    - gofmt
    - goimports
    - ineffassign
    - misspell
    - exportloopref
    - structcheck
    - typecheck
    - unconvert
    - unparam
    - varcheck
