name: Build
on: [push, pull_request]
jobs:
    build:
        name: Test
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                go: [ '1.17', '1.16', '1.15', '1.14' ]
                os: [ 'ubuntu-latest', 'macos-latest', 'windows-latest' ]
        steps:
            - uses: actions/checkout@v2
            - name: Setup go
              uses: actions/setup-go@v2
              with:
                go-version: ${{ matrix.go }}
            - uses: actions/cache@v2
              with:
                path: ~/go/pkg/mod
                key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
                restore-keys: |
                    ${{ runner.os }}-go-
            - name: Go Test
              run: go test -v ./...
    lint:
        name: Lint
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: golangci/golangci-lint-action@v2
              with:
                version: v1.42.1